#!/bin/sh

# TODO: enable fltk

autoreconf -vif

./configure \
	--prefix="$1/usr" \
	--localstatedir="$1/var" \
	--sysconfdir="$1/etc" \
	--enable-static \
	--with-opengl \
	--without-portaudio \
	--without-qt \
	--without-qscintilla \
	--without-fltk \
	--without-sndfile \
	--without-qhull

make
make install
