#!/bin/sh

# TODO: enable fltk

autoreconf -vif

./configure \
	--prefix="/usr" \
	--localstatedir="/var" \
	--sysconfdir="/etc" \
	--enable-static \
	--with-opengl \
	--without-portaudio \
	--without-qt \
	--without-qscintilla \
	--without-fltk \
	--without-sndfile \
	--without-qhull

make
make DESTDIR="$1" install
